---
# tasks file for iterm
- name: Checking if iTerm is installed
  stat: path=/Applications/iTerm.app/Contents/Info.plist
  register: iterm_plist

- name: Checking current version of iTerm
  shell: defaults read /Applications/iTerm.app/Contents/Info CFBundleVersion
  register: iterm_installed_version
  when: iterm_plist.stat.exists == True

- name: Remove currently installed iTerm
  file: path=/Applications/iTerm.app state=absent
  when: iterm_plist.stat.exists and iterm_installed_version.stdout != iterm_version

- name: Download iTerm
  get_url: url={{ url }} dest={{ iterm_temp_dir }}/{{ iterm_temp_file }}
  when: iterm_plist.stat.exists == False or (iterm_installed_version is defined and iterm_installed_version.stdout != iterm_version)

- name: Install iTerm
  unarchive: src={{ iterm_temp_dir }}/{{ iterm_temp_file }} dest=/Applications/
  when: iterm_plist.stat.exists == False or (iterm_installed_version is defined and iterm_installed_version.stdout != iterm_version)

- name: Remove iTerm setup file
  file: name={{ iterm_temp_dir }}/{{ iterm_temp_file }} state=absent
  when: iterm_plist.stat.exists == False or (iterm_installed_version is defined and iterm_installed_version.stdout != iterm_version)
